In [23]:
import pandas as pd

In [24]:
player_info = pd.read_csv("../data/player_info.csv", index_col=0)
player_info.head()

,name,country,age,hand,BuenosAires(2019/03),Cali(2019/05),Paris(2019/05),Tokyo(2019/06),Dusseldorf(2019/06),Bamako(2019/06),...,Berne(2019/11),Heidenheim(2020/01),Doha(2020/01),Vancouver(2020/02),Budapest(2020/03),total,before_Heidenheim WA,before_Vancouver WA,before_Budapest GP,in_match
1,BIDA Sergey,RUS,27.0,L,32.0,0.0,0.0,0.0,6.0,0.0,...,8.0,20.0,48.0,26.0,0.0,205.0,111.0,179.0,205.0,True
2,YAMADA Masaru,JPN,26.0,R,0.0,6.0,0.0,48.0,0.0,0.0,...,0.0,8.0,30.0,4.0,48.0,164.0,74.0,112.0,116.0,True
3,SIKLOSI Gergely,HUN,23.0,R,0.0,0.0,20.0,0.0,6.0,0.0,...,4.0,32.0,12.0,8.0,0.0,162.0,110.0,154.0,162.0,True
4,REIZLIN Igor,UKR,36.0,R,0.0,12.0,0.0,0.0,6.0,0.0,...,32.0,14.0,12.0,0.0,30.0,156.0,100.0,126.0,126.0,True
5,SANTARELLI Andrea,ITA,27.0,R,8.0,6.0,8.0,0.0,39.0,0.0,...,0.0,0.0,30.0,0.0,6.0,147.0,111.0,141.0,141.0,True

・name：名前
・age：年齢
・hand：利き手
・place(year/month)：大会時に獲得したポイント
・SA_alphabet：ほとんどだれも参加してない大会で面倒なのでこう書いた
・total：2020/10/20時点での獲得ポイント
・before_... : 大会前に獲得してたポイント(大会は20200708_fensing competiton.xlsxと同じ)

20200708_fensing competiton.xlsxの選手表記揺れも直してあります．

# 以下ゴミ

In [6]:
import numpy as np
import pandas as pd
import tabula
from tabula import wrapper

In [7]:
df_match = pd.read_excel("../data/20200708_fencing competiton.xlsx")
df_match.head(10)

    competition        name of game(fencer_NOC-fencer_NOC)  score
0  Vancouver WA       ALEXANIN Dmitriy_KAZ-SONG Jae Ho_KOR   9-15
1  Vancouver WA       BAYARD Alexis_SUI-PARK Sangyoung_KOR  12-13
2  Vancouver WA        BERTA Daniel_HUN-GAROZZO Enrico_ITA   8-15
3  Vancouver WA          BIDA Sergey_RUS-PRIINITS Sten_EST  15-13
4  Vancouver WA            BIDA Sergey_RUS-SONG Jae Ho_KOR  15-10
5  Vancouver WA             BIDA Sergey_RUS-WANG Zijie_CHN  13-12
6  Vancouver WA  BONNAIRE Jonathan_FRA-CIMINI Gabriele_ITA   8-15
7  Vancouver WA             BOREL Yannick_FRA-SYCH Yan_UKR  15-14
8  Vancouver WA      BRUNOLD Bruce_SUI-NIKISHIN Bogdan_UKR   4-15
9  Vancouver WA   CAMARGO Alexandre_BRA-CANNONE Romain_FRA  11-15

In [8]:
match = df_match["name of game(fencer_NOC-fencer_NOC)"].values.tolist()
names_inmatch = []
for m in match:
    m0, m1 = m.split("-")[0], m.split("-")[1]
    name0, name1 = m0.split("_")[0], m1.split("_")[0]
    names_inmatch.append(name0)
    names_inmatch.append(name1)
names_inmatch = list(set(names_inmatch))

In [15]:
df_player = pd.read_csv("../data/player_pt.csv", index_col=0)
df_player = df_player.where((df_player>0), 0)
# df_player = df_player.loc[df_player["age"]>10]
# names_inlist = df_player["name"].values.tolist()

In [13]:
for n in names_inmatch:
    if n not in names_inlist: print(n)

In [16]:
df_player.head(10)

,name,country,age,hand,BuenosAires(2019/03),Cali(2019/05),Paris(2019/05),Tokyo(2019/06),Dusseldorf(2019/06),Bamako(2019/06),...,SA_F,SA_G,SA_H,SA_I,Berne(2019/11),Heidenheim(2020/01),Doha(2020/01),Vancouver(2020/02),Budapest(2020/03),total
1,BIDA Sergey,RUS,27.0,L,32.0,0.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,8.0,20.0,48.0,26.0,0.0,205.0
2,YAMADA Masaru,JPN,26.0,R,0.0,6.0,0.0,48.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,8.0,30.0,4.0,48.0,164.0
3,SIKLOSI Gergely,HUN,23.0,R,0.0,0.0,20.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,4.0,32.0,12.0,8.0,0.0,162.0
4,REIZLIN Igor,UKR,36.0,R,0.0,12.0,0.0,0.0,6.0,0.0,...,0.0,0.0,0.0,0.0,32.0,14.0,12.0,0.0,30.0,156.0
5,SANTARELLI Andrea,ITA,27.0,R,8.0,6.0,8.0,0.0,39.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,6.0,147.0
6,BOREL Yannick,FRA,31.0,R,0.0,0.0,0.0,0.0,12.0,0.0,...,0.0,0.0,0.0,0.0,14.0,14.0,12.0,14.0,39.0,140.0
7,VERWIJLEN Bas,NED,37.0,R,0.0,3.0,0.0,0.0,21.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,21.0,32.0,6.0,122.0
8,PARK Sangyoung,KOR,25.0,R,0.0,12.0,32.0,12.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,26.0,12.0,8.0,0.0,112.0
9,MINOBE Kazuyasu,JPN,33.0,L,14.0,48.0,0.0,6.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,4.0,0.0,8.0,21.0,111.0
10,LIMARDO GASCON Ruben,VEN,35.0,L,8.0,0.0,8.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,20.0,6.0,108.0

In [17]:
df_player["before_Heidenheim WA"] = df_player.loc[:, "BuenosAires(2019/03)":"Berne(2019/11)"].values.sum(axis=1)
df_player["before_Vancouver WA"] = df_player.loc[:, "BuenosAires(2019/03)":"Doha(2020/01)"].values.sum(axis=1)
df_player["before_Budapest GP"] = df_player.loc[:, "BuenosAires(2019/03)":"Vancouver(2020/02)"].values.sum(axis=1)

df_player.head(10)

,name,country,age,hand,BuenosAires(2019/03),Cali(2019/05),Paris(2019/05),Tokyo(2019/06),Dusseldorf(2019/06),Bamako(2019/06),...,SA_I,Berne(2019/11),Heidenheim(2020/01),Doha(2020/01),Vancouver(2020/02),Budapest(2020/03),total,before_Heidenheim WA,before_Vancouver WA,before_Budapest GP
1,BIDA Sergey,RUS,27.0,L,32.0,0.0,0.0,0.0,6.0,0.0,...,0.0,8.0,20.0,48.0,26.0,0.0,205.0,111.0,179.0,205.0
2,YAMADA Masaru,JPN,26.0,R,0.0,6.0,0.0,48.0,0.0,0.0,...,0.0,0.0,8.0,30.0,4.0,48.0,164.0,74.0,112.0,116.0
3,SIKLOSI Gergely,HUN,23.0,R,0.0,0.0,20.0,0.0,6.0,0.0,...,0.0,4.0,32.0,12.0,8.0,0.0,162.0,110.0,154.0,162.0
4,REIZLIN Igor,UKR,36.0,R,0.0,12.0,0.0,0.0,6.0,0.0,...,0.0,32.0,14.0,12.0,0.0,30.0,156.0,100.0,126.0,126.0
5,SANTARELLI Andrea,ITA,27.0,R,8.0,6.0,8.0,0.0,39.0,0.0,...,0.0,0.0,0.0,30.0,0.0,6.0,147.0,111.0,141.0,141.0
6,BOREL Yannick,FRA,31.0,R,0.0,0.0,0.0,0.0,12.0,0.0,...,0.0,14.0,14.0,12.0,14.0,39.0,140.0,61.0,87.0,101.0
7,VERWIJLEN Bas,NED,37.0,R,0.0,3.0,0.0,0.0,21.0,0.0,...,0.0,0.0,4.0,21.0,32.0,6.0,122.0,59.0,84.0,116.0
8,PARK Sangyoung,KOR,25.0,R,0.0,12.0,32.0,12.0,0.0,0.0,...,0.0,0.0,26.0,12.0,8.0,0.0,112.0,66.0,104.0,112.0
9,MINOBE Kazuyasu,JPN,33.0,L,14.0,48.0,0.0,6.0,0.0,0.0,...,0.0,0.0,4.0,0.0,8.0,21.0,111.0,78.0,82.0,90.0
10,LIMARDO GASCON Ruben,VEN,35.0,L,8.0,0.0,8.0,0.0,0.0,0.0,...,0.0,8.0,0.0,0.0,20.0,6.0,108.0,82.0,82.0,102.0

In [20]:
df_player["in_match"] = df_player["age"] > 10

In [22]:
df_player.to_csv("../data/player_info.csv")